name: Homes
version: 2.0
api-version: 1.21
main: net.vertrauterdavid.homes.Homes
author: VertrauterDavid, JavaMio
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/
folia-supported: true
description: Fully customizable MySQL-based home system for Minecraft servers.

commands:
  homes:
  home: